package ui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;

/**
 *
 * @author Yan Chan Min Oo
 */
public class UIFrame extends javax.swing.JFrame {
	
	private LinkedList<String> holder; // Holds the list of user input

    /**
     * Creates new form UIFrame
     */
    public UIFrame() {
    	holder = new LinkedList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uiPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uiOutputField = new javax.swing.JTextArea();
        uiMaxWinBtn = new javax.swing.JButton();
        uiInputTextField = new javax.swing.JTextField();
        uiInputTextField.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				synchronized (holder) {
                    holder.add(uiInputTextField.getText());
                    holder.notify();
                }
                //frame.dispose();  
			}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uiPanel.setBackground(new java.awt.Color(49, 50, 49));

        uiOutputField.setEditable(false);
        uiOutputField.setBackground(new java.awt.Color(52, 43, 26));
        uiOutputField.setColumns(20);
        uiOutputField.setForeground(new java.awt.Color(255, 255, 204));
        uiOutputField.setRows(5);
        jScrollPane2.setViewportView(uiOutputField);

        uiMaxWinBtn.setBackground(new java.awt.Color(244, 230, 153));
        uiMaxWinBtn.setText(Character.toString((char)0x25B2));

        uiInputTextField.setBackground(new java.awt.Color(24, 24, 27));
        uiInputTextField.setForeground(new java.awt.Color(240, 240, 240));
        uiInputTextField.setCaretColor(Color.WHITE);

        javax.swing.GroupLayout uiPanelLayout = new javax.swing.GroupLayout(uiPanel);
        uiPanel.setLayout(uiPanelLayout);
        uiPanelLayout.setHorizontalGroup(
            uiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uiPanelLayout.createSequentialGroup()
                        .addComponent(uiInputTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uiMaxWinBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addContainerGap())
        );
        uiPanelLayout.setVerticalGroup(
            uiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uiPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(uiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiMaxWinBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        uiInputTextField.requestFocusInWindow();
    }// </editor-fold>//GEN-END:initComponents
    
    protected String getInputText(){
    	synchronized (holder) {
            // wait for input from field
            while (holder.isEmpty()) {
            	try{
            		holder.wait();
            	} catch(InterruptedException e){ }
            }

            return holder.remove(0);
        }
    }
    
    protected void setInputText(String s){
    	uiInputTextField.setText(s);
    }
    
    protected String getOutputText(){
    	return uiOutputField.getText();
    }
    
    protected void setOutputText(String s){
    	uiOutputField.setText(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField uiInputTextField;
    private javax.swing.JButton uiMaxWinBtn;
    private javax.swing.JTextArea uiOutputField;
    private javax.swing.JPanel uiPanel;
    // End of variables declaration//GEN-END:variables
}
